#: import main main

# 起動時に表示されるwidget
Test

<Row@BoxLayout>:
    #canvasへの色つけ
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos
    value: ''
    Label:
        text: root.value #それぞれのボタンを押して反映される値

#テストクラスで呼べるようにする
<Test>:
    canvas:
        Color:
            rgba: 0.3, 0.3, 0.3, 1
        Rectangle:
            size: self.size
            pos: self.pos
    rv: rv  #左辺のrvはPythonファイル上としてrvを呼び出すために使う，右辺のrvはkvファイルのRecycleViewのidとして使う
    orientation: 'vertical'
    GridLayout:
        cols: 3
        rows: 2
        size_hint_y: None
        height: dp(108)
        padding: dp(8)
        spacing: dp(16)
        Button:
            text: '人口リスト'
            on_press: root.populate()   #人口リストをクリックするとPythonファイルのpopulate関数が呼ばれる
        Button:
            text: '昇順に変更'
            on_press: root.sort()
        Button:
            text: 'リストの全消去'
            on_press: root.clear()
        BoxLayout:
            spacing: dp(8)
            Button:
                text: 'データの挿入'
                on_press: root.insert(new_item_input.text)  #new_item_inputはTextInputのidで宣言
            TextInput:
                id: new_item_input
                size_hint_x: 0.6
                hint_text: '文字を入力'  #薄文字で表示
                padding: dp(10), dp(10), 0, 0
        BoxLayout:
            spacing: dp(8)
            Button:
                text: 'データの更新'
                on_press: root.update(update_item_input.text) #update_item_inputはTextInputのidで宣言
            TextInput:
                id: update_item_input
                size_hint_x: 0.6
                hint_text: '先頭を変更'
                padding: dp(10), dp(10), 0, 0
        Button:
            text: '1データ削除'
            on_press: root.remove()

    RecycleView:
        id: rv  #Canvasを反映させるため
        scroll_type: ['bars', 'content']
        scroll_wheel_distance: dp(114)
        bar_width: dp(10)
        viewclass: 'Row'
        RecycleBoxLayout:
            default_size: None, dp(56)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
            spacing: dp(2)